// <auto-generated />
using System;
using GoldSrcOps.AlertReceiver.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GoldSrcOps.AlertReceiver.Persistence.Migrations
{
    [DbContext(typeof(AlertReceiverDbContext))]
    [Migration("20260918180602_InitialAlertReceiver")]
    partial class InitialAlertReceiver
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("receiver")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GoldSrcOps.AlertReceiver.Persistence.ProviderOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("SourceEventId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId");

                    b.HasIndex("SourceEventId")
                        .IsUnique()
                        .HasDatabaseName("UX_receiver_provider_outbox_SourceEventId");

                    b.HasIndex("Status", "NextAttemptAtUtc", "CreatedAtUtc", "Id")
                        .HasDatabaseName("IX_receiver_provider_outbox_pending")
                        .HasFilter("\"Status\" = 'Pending'");

                    b.ToTable("provider_outbox_messages", "receiver", t =>
                        {
                            t.HasCheckConstraint("CK_receiver_provider_outbox_AttemptCount", "\"AttemptCount\" >= 0");
                        });
                });

            modelBuilder.Entity("GoldSrcOps.AlertReceiver.Persistence.ReceivedAvailabilityEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("PayloadSha256")
                        .IsRequired()
                        .HasColumnType("character(64)");

                    b.Property<short>("PayloadVersion")
                        .HasColumnType("smallint");

                    b.Property<bool>("ProviderActionSuppressed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReceiverMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId", "OccurredAtUtc", "Id");

                    b.ToTable("events", "receiver", t =>
                        {
                            t.HasCheckConstraint("CK_receiver_events_PayloadVersion", "\"PayloadVersion\" = 1");

                            t.HasCheckConstraint("CK_receiver_events_Suppression", "(\"ReceiverMode\" = 'CatchUp' AND \"ProviderActionSuppressed\")\nOR (\"ReceiverMode\" = 'Live' AND NOT \"ProviderActionSuppressed\")");
                        });
                });

            modelBuilder.Entity("GoldSrcOps.AlertReceiver.Persistence.ReceiverIncident", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastEventAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LastEventId")
                        .HasColumnType("uuid");

                    b.Property<string>("OpenReason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("OpenedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResolutionReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ServerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("State", "LastEventAtUtc");

                    b.HasIndex("ServerId", "State", "OpenedAtUtc");

                    b.ToTable("incidents", "receiver", t =>
                        {
                            t.HasCheckConstraint("CK_receiver_incidents_ConsecutiveFailures", "\"ConsecutiveFailures\" > 0");

                            t.HasCheckConstraint("CK_receiver_incidents_Revision", "\"Revision\" > 0");

                            t.HasCheckConstraint("CK_receiver_incidents_StateFields", "(\"State\" = 'Open'\n    AND \"ClosedAtUtc\" IS NULL\n    AND \"ResolutionReason\" IS NULL)\nOR (\"State\" = 'Resolved'\n    AND \"ClosedAtUtc\" IS NOT NULL\n    AND \"ResolutionReason\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("GoldSrcOps.AlertReceiver.Persistence.ProviderOutboxMessage", b =>
                {
                    b.HasOne("GoldSrcOps.AlertReceiver.Persistence.ReceiverIncident", null)
                        .WithMany()
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GoldSrcOps.AlertReceiver.Persistence.ReceivedAvailabilityEvent", null)
                        .WithOne()
                        .HasForeignKey("GoldSrcOps.AlertReceiver.Persistence.ProviderOutboxMessage", "SourceEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GoldSrcOps.AlertReceiver.Persistence.ReceivedAvailabilityEvent", b =>
                {
                    b.HasOne("GoldSrcOps.AlertReceiver.Persistence.ReceiverIncident", null)
                        .WithMany()
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
