// <auto-generated />
using System;
using GoldSrcOps.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GoldSrcOps.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GoldSrcOpsDbContext))]
    [Migration("20260824153238_AddAlertOutboxPersistence")]
    partial class AddAlertOutboxPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("goldsrcops")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GoldSrcOps.Domain.Commands.CommandExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Payload")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("RequestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ResultSummary")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Status", "StartedAtUtc");

                    b.HasIndex("ServerId", "Status", "RequestedAtUtc");

                    b.ToTable("command_executions", "goldsrcops");
                });

            modelBuilder.Entity("GoldSrcOps.Domain.Servers.AvailabilityIncident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("integer");

                    b.Property<string>("EndReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("OpenedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid");

                    b.Property<string>("StartReason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("ServerId", "ClosedAtUtc");

                    b.ToTable("availability_incidents", "goldsrcops");
                });

            modelBuilder.Entity("GoldSrcOps.Domain.Servers.PollSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Bots")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CheckedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsReachable")
                        .HasColumnType("boolean");

                    b.Property<int?>("LatencyMs")
                        .HasColumnType("integer");

                    b.Property<string>("Map")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int?>("MaxPlayers")
                        .HasColumnType("integer");

                    b.Property<int?>("Players")
                        .HasColumnType("integer");

                    b.Property<string>("RawVersion")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CheckedAtUtc", "Id")
                        .HasAnnotation("Npgsql:CreatedConcurrently", true);

                    b.HasIndex("ServerId", "CheckedAtUtc");

                    b.ToTable("poll_snapshots", "goldsrcops");
                });

            modelBuilder.Entity("GoldSrcOps.Domain.Servers.Server", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Game")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("PollIntervalSeconds")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("servers", "goldsrcops");
                });

            modelBuilder.Entity("GoldSrcOps.Domain.Servers.ServerCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SecretReference")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ServerId", "Kind")
                        .IsUnique();

                    b.ToTable("server_credentials", "goldsrcops");
                });

            modelBuilder.Entity("GoldSrcOps.Domain.Servers.ServerCurrentState", b =>
                {
                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("integer");

                    b.Property<string>("CurrentMap")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsReachable")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastCheckedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastSuccessAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LatencyMs")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxPlayers")
                        .HasColumnType("integer");

                    b.Property<int?>("Players")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("ServerId");

                    b.ToTable("server_current_states", "goldsrcops");
                });

            modelBuilder.Entity("GoldSrcOps.Infrastructure.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ClaimId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ClaimedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<short>("PayloadVersion")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("EventType", "AggregateId")
                        .IsUnique()
                        .HasDatabaseName("UX_outbox_messages_EventType_AggregateId");

                    b.HasIndex("ProcessedAtUtc", "Id")
                        .HasDatabaseName("IX_outbox_messages_processed_cleanup")
                        .HasFilter("\"Status\" = 'Processed'");

                    b.HasIndex("Status", "ClaimedAtUtc")
                        .HasDatabaseName("IX_outbox_messages_processing_recovery")
                        .HasFilter("\"Status\" = 'Processing'");

                    b.HasIndex("AggregateType", "AggregateId", "OccurredAtUtc", "Id")
                        .HasDatabaseName("IX_outbox_messages_active_aggregate_order")
                        .HasFilter("\"Status\" IN ('Pending', 'Processing')");

                    b.HasIndex("Status", "NextAttemptAtUtc", "OccurredAtUtc", "Id")
                        .HasDatabaseName("IX_outbox_messages_pending_claim")
                        .HasFilter("\"Status\" = 'Pending'");

                    b.ToTable("outbox_messages", "goldsrcops", t =>
                        {
                            t.HasCheckConstraint("CK_outbox_messages_AttemptCount", "\"AttemptCount\" >= 0");

                            t.HasCheckConstraint("CK_outbox_messages_PayloadVersion", "\"PayloadVersion\" > 0");

                            t.HasCheckConstraint("CK_outbox_messages_StatusFields", "(\"Status\" = 'Pending'\n    AND \"ClaimId\" IS NULL\n    AND \"ClaimedAtUtc\" IS NULL\n    AND \"ProcessedAtUtc\" IS NULL)\nOR (\"Status\" = 'Processing'\n    AND \"ClaimId\" IS NOT NULL\n    AND \"ClaimedAtUtc\" IS NOT NULL\n    AND \"ProcessedAtUtc\" IS NULL)\nOR (\"Status\" = 'Processed'\n    AND \"ClaimId\" IS NULL\n    AND \"ClaimedAtUtc\" IS NULL\n    AND \"ProcessedAtUtc\" IS NOT NULL)\nOR (\"Status\" = 'DeadLetter'\n    AND \"ClaimId\" IS NULL\n    AND \"ClaimedAtUtc\" IS NULL\n    AND \"ProcessedAtUtc\" IS NULL)");
                        });
                });

            modelBuilder.Entity("GoldSrcOps.Domain.Commands.CommandExecution", b =>
                {
                    b.HasOne("GoldSrcOps.Domain.Servers.Server", "Server")
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("GoldSrcOps.Domain.Servers.AvailabilityIncident", b =>
                {
                    b.HasOne("GoldSrcOps.Domain.Servers.Server", "Server")
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("GoldSrcOps.Domain.Servers.PollSnapshot", b =>
                {
                    b.HasOne("GoldSrcOps.Domain.Servers.Server", "Server")
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("GoldSrcOps.Domain.Servers.Server", b =>
                {
                    b.OwnsOne("GoldSrcOps.Domain.Servers.ServerEndpoint", "Endpoint", b1 =>
                        {
                            b1.Property<Guid>("ServerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Host")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("host");

                            b1.Property<int>("QueryPort")
                                .HasColumnType("integer")
                                .HasColumnName("query_port");

                            b1.Property<int?>("RconPort")
                                .HasColumnType("integer")
                                .HasColumnName("rcon_port");

                            b1.HasKey("ServerId");

                            b1.ToTable("servers", "goldsrcops");

                            b1.WithOwner()
                                .HasForeignKey("ServerId");
                        });

                    b.Navigation("Endpoint")
                        .IsRequired();
                });

            modelBuilder.Entity("GoldSrcOps.Domain.Servers.ServerCredential", b =>
                {
                    b.HasOne("GoldSrcOps.Domain.Servers.Server", "Server")
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("GoldSrcOps.Domain.Servers.ServerCurrentState", b =>
                {
                    b.HasOne("GoldSrcOps.Domain.Servers.Server", "Server")
                        .WithOne("CurrentState")
                        .HasForeignKey("GoldSrcOps.Domain.Servers.ServerCurrentState", "ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("GoldSrcOps.Domain.Servers.Server", b =>
                {
                    b.Navigation("CurrentState");
                });
#pragma warning restore 612, 618
        }
    }
}
